// generated by Textmapper; DO NOT EDIT

package ast

import (
	"fmt"
	"github.com/ddosakura/sakura-cat/tm-test/grammar"
)

func ToSkrNode(n *Node) SkrNode {
	switch n.Type() {
	case grammar.BindingIdentifier:
		return &BindingIdentifier{n}
	case grammar.FunctionType:
		return &FunctionType{n}
	case grammar.InterfaceItem:
		return &InterfaceItem{n}
	case grammar.InterfaceType:
		return &InterfaceType{n}
	case grammar.LiteralType:
		return &LiteralType{n}
	case grammar.ParameterList:
		return &ParameterList{n}
	case grammar.PredefinedType:
		return &PredefinedType{n}
	case grammar.RetList:
		return &RetList{n}
	case grammar.StructType:
		return &StructType{n}
	case grammar.MultiLineComment, grammar.SingleLineComment, grammar.InvalidToken:
		return &Token{n}
	case grammar.NoType:
	  return nilInstance
	}
	panic(fmt.Errorf("ast: unknown node type %v", n.Type()))
	return nil
}
